### ISSUE TITLE
Put "Where Are You Working" Map in place of Video

### ISSUE THREAD

**Issue by berwinxie** [IllinoisWCS/IllinoisWCS.github.io#102]
Currently, it makes the repository very large since the video is > 80mb. git clone took many moments because of this. Maybe we can upload to some video service instead of serving it from github static page.

Possibilities:
Google drive
Youtube
Vimeo

**Comment by sskhandek** [comment]
@vivekvaidya Instead, can this be just to put an embedded map instead of that video?

**Comment by sskhandek** [comment]
<iframe class="member-map" src="https://www.google.com/maps/d/embed?mid=1Ke1I6UgBfBUVkb4uk3OWacUI3jg"></iframe>

**Comment by vivekvaidya** [comment]
Also while working on this I found a lot of assets from legacy versions of the website - maybe we should remove those, especially since GitHub preserves said legacy versions anyway

**Comment by sskhandek** [comment]
If you want to delete them, please do. I don't care <3

**Comment by vivekvaidya** [comment]
> best webmaster ever
