### ISSUE TITLE
Footer Position isn't responsive/absolute

### ISSUE THREAD

**Issue by tyler-thetyrant** [IllinoisWCS/IllinoisWCS.github.io#107]
![screen shot 2017-03-06 at 11 28 37 pm](https://cloud.githubusercontent.com/assets/12504517/23643016/a51997f4-02c4-11e7-9ee1-7850c9e75275.png)

![screen shot 2017-03-06 at 11 26 13 pm](https://cloud.githubusercontent.com/assets/12504517/23642974/5fda48aa-02c4-11e7-86f9-51a1e38ce612.png)

![screen shot 2017-03-06 at 11 27 55 pm](https://cloud.githubusercontent.com/assets/12504517/23642995/8a3e1ba8-02c4-11e7-9a52-0e7dfce828cd.png)

Also the footer is missing on the Officer and the Sponsors page.

**Comment by sskhandek** [comment]
Thanks @tyler-thetyrant ! I'll take this one
