### ISSUE TITLE
Point Tracker is broken

### ISSUE THREAD

**Issue by berwinxie** [IllinoisWCS/IllinoisWCS.github.io#108]
From the main page, the point tracker link goes to a broken link, not sure if it is still accessible.

<img width="253" alt="screen shot 2017-03-08 at 01 01 11" src="https://cloud.githubusercontent.com/assets/5169056/23693593/ca01337a-039a-11e7-8ec5-db98ba565656.png">

**Comment by vivekvaidya** [comment]
the point tracker itself doesn't seem to be working. cc: @sskhandek

**Comment by elchao96** [comment]
Point checker is still fine. http://wcs.illinois.edu/members/#points Just not sure about linking.

**Comment by berwinxie** [comment]
The hyperlink on the main page is going to [http://wcs.illinois.edu/members/points#](http://wcs.illinois.edu/members/points#) instead of [http://wcs.illinois.edu/members/#points](http://wcs.illinois.edu/members/#points)

AKA the pound sign is in the wrong place
