### ISSUE TITLE
Mustache imports for head section in subpages

### ISSUE THREAD

**Issue by sskhandek** [IllinoisWCS/IllinoisWCS.github.io#121]
Currently, the project has Mustache (https://github.com/janl/mustache.js) installed so we can do some templating. One pain point has been that we keep re-writing the same link and script tags in the head section of each page and it can be pretty inconsistent. It would be nice to write this once and then import it with some templating from Mustache.

**Comment by vivekvaidya** [comment]
I can work on this but need some handholding

**Comment by sskhandek** [comment]
@vivekvaidya Thanks! Check out the official website for examples:https://github.com/janl/mustache.js#usage 

You can also look at a code example here: https://github.com/IllinoisWCS/IllinoisWCS.github.io/blob/master/assets/js/officers.js#L1

Moreover, I erroneously named this issue with "handlebars", another similar templating library. If you can find more noticeable differences between the two, we'd appreciate input into which we should use going forward. 

We can also discuss more at the Webmonkeys meeting on Tuesday if you can make it!

**Comment by vivekvaidya** [comment]
I'm free Tuesday at 7pm, which is after the Webmonkeys meeting but we can still talk if it works for you.

**Comment by sskhandek** [comment]
Let's coordinate over chat :)
