### ISSUE TITLE
Revamp resource page for opportunities for women/minorities in tech

### ISSUE THREAD

**Issue by elchao96** [IllinoisWCS/IllinoisWCS.github.io#33]
- FB groups
- Slack channels
- Conferences
- Scholarships
- Publications on Medium
- Twitter accounts
- Cool influencers
- Internship Programs

**Comment by sskhandek** [comment]
@elchao96 Did you have a chance to work on this? Just checking in? Did you need any help?

**Comment by elchao96** [comment]
I'm getting started on it today. Sorry for delay.

**Comment by sskhandek** [comment]
@elchao96 Thank you!
