### ISSUE TITLE
Add Travis-Ci Tests

### ISSUE THREAD

**Issue by sskhandek** [IllinoisWCS/IllinoisWCS.github.io#44]

**Comment by ananyacleetus** [comment]
@sskhandek what is this issue?

**Comment by elchao96** [comment]
@sskhandek Are you thinking of doing selenium tests? Endpoint tests? I'm not sure what we would want to test here...

**Comment by sskhandek** [comment]
@ananyacleetus @elchao96 https://travis-ci.org/ 

It was more for testing. Ignore for now. It's a future reach goal.

**Comment by sskhandek** [comment]
Closing for now
