### ISSUE TITLE
Add Jing to the Officers

### ISSUE THREAD

**Issue by elchao96** [IllinoisWCS/IllinoisWCS.github.io#46]
I think Bootstrap has a default picture for an avatar until we can get a picture for her?

**Comment by sskhandek** [comment]
@elchao96 Do you know how we can get the rest of her information?

**Comment by JingHuang81** [comment]
@sskhandek Are you looking for the information to fill up the name card on the website? I can provide you that over slack.

**Comment by sskhandek** [comment]
@JingHuang81 can you give me the rest of the information like what's given here? You can slack me them and Ill give them to @linahsie  https://github.com/IllinoisWCS/IllinoisWCS.github.io/blob/master/assets/js/officers.js

**Comment by sskhandek** [comment]
@linahsie , it's attached below. Plz wait until I merge Surabhi's PR first so you can make sure we put it in the right file.

{
         "position": "Tech Team Co-Chair",
         "firstname": "Jing",
         "lastname": "Huang",
         "email": "jhuang81@illinois.edu",
         "netid": "jhuang81",
         "year": "Junior",
         "major": "Computer Science",
         "interests": [
             "Machine Learning",
             "Algorithms"
         ],
         "experience": [
           "CS 233 Course Assistant",
           "Software Engineering Intern, Google, Summer 2016",
           "Technology Developer and Analyst Intern, Bank of America, Summer 2015"
         ],
         "hobbies": [
             "Writing",
             "Badminton"
         ],
         "fact": "I grew up in Beijing but never visited the Forbidden City.",
         "place": "Beijing, China",
         "ask": []
       }

**Comment by sskhandek** [comment]
@linahsie Go ahead and get started on this 👍  Please ```git pull``` on the master branch before you create a new branch!

**Comment by linahsie** [comment]
@sskhandek do you have her picture?

**Comment by sskhandek** [comment]
@JingHuang81 Do you have a preferred picture? 😄

**Comment by JingHuang81** [comment]
@sskhandek Could we go with Emily's suggestion for now? Not sure if I have a picture that can fit into the rest.
