### ISSUE TITLE
Alumni Page

### ISSUE THREAD

**Issue by linahsie** [IllinoisWCS/IllinoisWCS.github.io#56]
Do we want to include this in the main page? If yes, maybe fix the image layout? wcs.illinois.edu/alumni

**Comment by sskhandek** [comment]
@meghatron3000 Did you want to try this out? I can onboard you in person if you need help with creating branches and stuff

**Comment by meghatron3000** [comment]
I can try this out! I just created a branch thank you @sskhandek

**Comment by meghatron3000** [comment]
Creating a new issue about working on the alumni subpage instead of integrating it with the main page
