### ISSUE TITLE
Can't see anybody's face except for Corly and Vaishali on the front page

### ISSUE THREAD

**Issue by ShivaliPatel2** [IllinoisWCS/IllinoisWCS.github.io#68]
can we fix the placement of the picture on the front page? it blocks most people's faces

**Comment by sskhandek** [comment]
@ShivaliPatel2 Can you post a screenshot? We may also talk about a redesign today so this may not be an issue.

**Comment by ericanylee** [comment]
![screen shot 2017-02-01 at 2 29 08 pm](https://cloud.githubusercontent.com/assets/16003400/22524933/d69d7434-e88a-11e6-831e-6ccfefe9b277.png)

**Comment by vivekvaidya** [comment]
<img width="1434" alt="but" src="https://cloud.githubusercontent.com/assets/10797230/22524991/1219947a-e88b-11e6-9fa7-ae2020a2a8ca.png">

but...

**Comment by ShivaliPatel2** [comment]
I'm away from my computer but also I'm pretty sure the current pic cuts out some officers, ie erica and shannon b

**Comment by sskhandek** [comment]
@ShivaliPatel2 I'm closing this since we're redoing the homepage. Thank you for the feedback.
