### ISSUE TITLE
Get Proper Icon Set

### ISSUE THREAD

**Issue by sskhandek** [IllinoisWCS/IllinoisWCS.github.io#81]
<img width="299" alt="screen shot 2017-02-03 at 2 12 57 pm" src="https://cloud.githubusercontent.com/assets/5349493/22606827/e4cc861c-ea1a-11e6-8772-f2cf1a953b65.png">

We need individual icons for favicons, etc. It maybe worthwhile talking to kavya

**Comment by vivekvaidya** [comment]
should we consider a logo redesign?

**Comment by sskhandek** [comment]
@vivekvaidya That's probably a higher level conversation that we need to have with Corly and Kavya since she's publicity chair.

**Comment by sskhandek** [comment]
Here's the logo by itself. Can we add this to our project and create favicons for this too?

https://drive.google.com/a/illinois.edu/file/d/0B1lw0v0xVwaWZWpiRXVNNjNseWs/view?usp=sharing

**Comment by linahsie** [comment]
@sskhandek i found this: http://www.favicon-generator.org/ is that what you want? just an icon for the tabs?

**Comment by sskhandek** [comment]
@linahsie yup! exactly

**Comment by sskhandek** [comment]
Thank you @linahsie ! This got pushed to master!
