### ISSUE TITLE
Add the following to the resources page

### ISSUE THREAD

**Issue by elchao96** [IllinoisWCS/IllinoisWCS.github.io#86]
Facebook Groups
- Ladies Storm Hackathons (and subsequent groups)
- Hackathon Hackers (and subsequent HH [X] groups)
- Tech Ladies (https://www.hiretechladies.com/)
- CS+Social Good (originally started from Stanford)

Slack Channels
- LGBTQ in Tech (lgbt.slack.com)
- Frontend Developers (frontenddevelopers.slack.com)
- Slashrocket (slashrocket.io)

Influencers
- Tracy Chou (former software engineer at Pinterest and Quora, involved with Project Include, a non-profit that works to help companies improve their employee diversity and inclusion, jumpstarted the movement to encourage companies to release their diversity numbers)
- Project Include staff - Ellen Pao (former CEO of reddit), Laura Gomez (founder of Atipica, a startup that aims to disrupt current tech hiring with an emphasis on diversity), Erica Baker (engineer at Slack), Bethanye McKinney Blount, Y-Vonne Hutchinson, Freada Kapor Klein, Susan Wu
- Cassidy Williams (software engineer at L4Digital, moderator for HH, heavily involved in women in tech movements)
- Laura Weidman Powers (cofounder of Code2040)
- Kimberly Bryant (founder of BlackGirlsCode)
- Megan Smith (former CTO of the United States, former Google engineer)
- Anil Dash (CEO of Fog Creek Software, prolific blogger regarding ethics and technology)
- Parisa Tabriz (head of Google Chrome Security, also affectionately known as Google's Security Princess, UIUC alum!)
- Amy Chen (founder of Ladies Storm Hackathons Facebook group)

Feel free to add and pick and choose based on discretion.

**Comment by sskhandek** [comment]
@ssonali2 @meghatron3000 @linahsie Anyone?

**Comment by vivekvaidya** [comment]
done
