### ISSUE TITLE
Reduce font size and spacing of events section

### ISSUE THREAD

**Issue by sskhandek** [IllinoisWCS/IllinoisWCS.github.io#90]
<img width="547" alt="screen shot 2017-02-15 at 5 12 34 pm" src="https://cloud.githubusercontent.com/assets/5349493/22999610/f9c7de5a-f3a1-11e6-8c7d-e2b886990687.png">

**Comment by vivekvaidya** [comment]
events don't render on Safari - should we fix that first?

**Comment by vivekvaidya** [comment]
can we close this? I think the font size is fine although the issue of rendering remains

**Comment by sskhandek** [comment]
I think this one is really close. I'd prefer if only the headers would have that orange color. If we can just make these black that'd be good. I can quickly fix that.
