### ISSUE TITLE
Mobile Background image broken

### ISSUE THREAD

**Issue by Crongz** [IllinoisWCS/IllinoisWCS.github.io#95]
<img width="401" alt="screen shot 2017-02-21 at 7 12 40 pm" src="https://cloud.githubusercontent.com/assets/8813519/23192581/e082abf6-f869-11e6-9c6a-8ccc06880502.png">

Cite - Devin Ho The God Of CSS

**Comment by sskhandek** [comment]
Thanks @Crongz this should be fixed in an upcoming version of the site
